#ddev-generated

USER $username

# TODO: Require a stable version
RUN composer global require --no-cache upstreamable/ddev-basin:dev-main && \
  ln -s ~/.composer/vendor/bin/basin.php /usr/local/bin/basin

# Switch back to root for other dockerfiles
USER root
