#!/usr/bin/env bash
#ddev-generated

## Description: Run commands on the host required by a container
## Usage: basin-host-commands
## Example: ddev basin-host-commands

# Directory to search for *.env files
dir="${DDEV_APPROOT}/.ddev/commands/basin"

# Unmatched globs expand to nothing, not the literal pattern
shopt -s nullglob
for f in "$dir"/*.env; do
  # skip if not a regular file (or if no matches)
  [ -f "$f" ] || continue
  source "$f"
  rm $f

  case "$BASIN_COMMAND" in
    add-on-get)
      # Add --version only when is non-empty
      ddev add-on get "$BASIN_ADDON" ${BASIN_ADDON_VERSION:+--version "$BASIN_ADDON_VERSION"}
      ;;
    ddev-restart)
      ddev restart
      ;;
    "")
      ;;
    *)
      ;;
  esac
done

