#!/usr/bin/env bash
#ddev-generated

## Description: Config a Basin Drupal project
## Usage: config-drupal-basin
## Example: "ddev config-drupal-basin"
## CanRunGlobally: true

# Exit on error or pipefail
set -eo pipefail

ddev config-drupal
ddev config-drupal-extras
ddev config-drupal-redis
