services:
    _defaults:
        autowire: true
        autoconfigure: true

    Basin\Command\:
        resource: '../../src/Command/'
        tags: ['console.command']

    Symfony\Component\Console\Application:
        public: true
        arguments:
            $name: Basin
            $version: 1.0.0
        calls:
            - setCommandLoader: ['@console.command_loader']
